In [ ]:
# Name : Robins Yadav
# Roll : 24BECSE47
# PS : Perform Clustering using K-Means
from sklearn.cluster import KMeans
import numpy as np

In [2]:
# Step 1: Input daily tasks
tasks = [
    {"name": "Studying", "time": 120, "urgency": 9, "effort": 8},
    {"name": "Gym", "time": 60, "urgency": 6, "effort": 7},
    {"name": "Assignments", "time": 180, "urgency": 10, "effort": 9},
    {"name": "Netflix", "time": 90, "urgency": 2, "effort": 2},
    {"name": "Urgent Work", "time": 150, "urgency": 10, "effort": 8},
]

In [3]:
# Step 2: Convert tasks into numerical features
X = np.array([[t["time"], t["urgency"], t["effort"]] for t in tasks])

In [4]:
print(X)

[[120   9   8]
 [ 60   6   7]
 [180  10   9]
 [ 90   2   2]
 [150  10   8]]


In [5]:
# Step 3: Apply K-Means (3 clusters: High, Medium, Low)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
labels = kmeans.fit_predict(X)

In [6]:
print(labels)

[2 0 1 0 1]


In [7]:
# Step 4: Interpret clusters based on urgency (smart mapping)
centroids = kmeans.cluster_centers_

In [8]:
# Sort clusters by urgency (higher urgency = higher priority)
priority_order = np.argsort(-centroids[:, 1])  # sort descending by urgency
priority_map = {}
priority_names = ["| High |", "| Medium |", "| Low |"]

In [9]:
for i, cluster_index in enumerate(priority_order):
    priority_map[cluster_index] = priority_names[i]

In [10]:
# Step 5: Display results
print("\n Task Prioritization using K-Means:\n")

for i, task in enumerate(tasks):
    cluster = labels[i]
    priority = priority_map[cluster]
    print(f"{task['name']:15} → {priority} Priority")


 Task Prioritization using K-Means:

Studying        → | Medium | Priority
Gym             → | Low | Priority
Assignments     → | High | Priority
Netflix         → | Low | Priority
Urgent Work     → | High | Priority


In [11]:
# Step 6: Show cluster centers (for understanding)
print("\nCluster Centers (Time, Urgency, Effort):\n")
for i, center in enumerate(centroids):
    print(f"Cluster {i}: {center}")


Cluster Centers (Time, Urgency, Effort):

Cluster 0: [75.   4.   4.5]
Cluster 1: [165.   10.    8.5]
Cluster 2: [120.   9.   8.]
